version: "3"
services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    hostname: oracle-bestia
    environment:
      - PUID=1001 # Usuario 'ubuntu' en Oracle Cloud
      - PGID=1001
      - TZ=Europe/Madrid
    volumes:
      - ./config:/config
      - ./data:/data # Carpeta de sincronizaci√≥n
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
